FROM ubuntu:16.04
RUN mkdir -p /opt/app
WORKDIR /opt/app
RUN apt-get update && apt-get install -y \
  ca-certificates \
  libgmp-dev

COPY ./healths .

ENV HEALTHS_PORT 8080
ENV HEALTHS_INFLUXHOST influxdb
ENV HEALTHS_DATABASE /data/state.json
EXPOSE 8080
ENTRYPOINT ["/opt/app/healths"]
