version: "3.7"
services:

  healths:
    image: utky/healths:dev
    ports:
      - "8080:8080"
    links:
      - influxdb
    volumes:
      - type: volume
        source: healths-data
        target: /data
    command: -i influxdb -d /data/state.json -p 8080

  influxdb:
    image: influxdb:1.6-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb

  grafana:
    image: grafana/grafana:5.2.3
    ports:
      - "8087:3000"
    links:
      - influxdb
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana

volumes:
  healths-data:
  influxdb-data:
  grafana-data:
