name:                healths
version:             0.1.0.0
github:              "utky/healths"
license:             BSD3
author:              "Yutaka Imamura"
maintainer:          "ilyaletre@gmail.com"
copyright:           "2018 Yutaka Imamura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/utky/healths#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- aeson
- Spock
- wai
- text
- containers
- time
- bytestring
- blaze-html
- influxdb
- lens
- directory
- stm
- free

library:
  source-dirs: src

executables:
  healths:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - healths

tests:
  healths-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - healths
    - Spock
    - hspec
    - hspec-wai
    - aeson
    - time
    - QuickCheck
